import React, { useEffect, useRef, useState } from "react";

/**
 * App.jsx
 *
 * Usage: Accepts data via query parameters:
 * - problem_name_te
 * - problem_name_en
 * - category
 * - stage
 * - symptoms_te
 * - notes_te
 * - components  -> JSON stringified array of component objects (UTF-8)
 * - receipt_id
 *
 * Example URL:
 * https://your-vercel.app/?problem_name_te=...&components=%5B%7B%22component_type%22%3A%22...%22%7D%5D&receipt_id=ADV-...
 *
 * IMPORTANT: If data is very large, consider passing only receipt_id and let this app call your Hostinger API to fetch the data.
 */

const readQuery = (key) => {
  const params = new URLSearchParams(window.location.search);
  return params.get(key);
};

const safeDecode = (v) => {
  try {
    return v ? decodeURIComponent(v) : null;
  } catch (e) {
    return v;
  }
};

const parseComponents = (str) => {
  if (!str) return [];
  try {
    // components may be URL encoded JSON
    const decoded = safeDecode(str);
    return JSON.parse(decoded);
  } catch (e) {
    // fallback: attempt raw parse
    try {
      return JSON.parse(str);
    } catch (e2) {
      return [];
    }
  }
};

export default function App() {
  const pdfRef = useRef(null);
  const [autoGenerated, setAutoGenerated] = useState(false);

  // Read data from URL
  const problem_name_te = safeDecode(readQuery("problem_name_te")) || "";
  const problem_name_en = safeDecode(readQuery("problem_name_en")) || "Advisory";
  const category = safeDecode(readQuery("category")) || "-";
  const stage = safeDecode(readQuery("stage")) || "-";
  const symptoms_te = safeDecode(readQuery("symptoms_te")) || "";
  const notes_te = safeDecode(readQuery("notes_te")) || "";
  const components = parseComponents(readQuery("components"));
  const receipt_id = safeDecode(readQuery("receipt_id")) || `ADV-${Date.now()}`;

  // Date/time in IST
  const dateIST = new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" });

  useEffect(() => {
    // Wait until DOM paints and fonts load
    const timer = setTimeout(() => {
      // if html2pdf available global (via CDN)
      if (window && typeof window.html2pdf === "function" && pdfRef.current && !autoGenerated) {
        const element = pdfRef.current;

        const opt = {
          margin: [5, 3, 5, 3], // top, left, bottom, right in mm (approx)
          filename: `advisory_receipt_${receipt_id}.pdf`,
          image: { type: "jpeg", quality: 0.98 },
          html2canvas: { scale: 2, useCORS: true },
          jsPDF: { unit: "mm", format: [80, 120], orientation: "portrait" },
        };

        try {
          window.html2pdf().set(opt).from(element).save();
          setAutoGenerated(true);
        } catch (err) {
          console.error("html2pdf error:", err);
        }
      } else {
        // If html2pdf not loaded, console notice
        if (!window.html2pdf) {
          console.error("html2pdf not found. Ensure CDN script in index.html is available.");
        }
      }
    }, 900); // ~1s delay to let fonts load

    return () => clearTimeout(timer);
  }, [autoGenerated, receipt_id]);

  // Inline styles similar to pdf styles from PHP version
  const styles = {
    container: {
      width: "80mm",
      padding: "6px",
      fontFamily: "Lexend, Arial, sans-serif",
      fontSize: "10px",
      lineHeight: 1.3,
      color: "#000",
    },
    header: {
      textAlign: "center",
      marginBottom: "6px",
      borderBottom: "1px dashed #000",
      paddingBottom: "6px",
    },
    logo: {
      height: "60px",
      display: "block",
      margin: "0 auto 4px",
    },
    companyName: {
      fontWeight: "700",
      fontSize: "14px",
      margin: "2px 0",
    },
    companyTag: {
      fontSize: "9px",
      fontStyle: "italic",
      margin: "2px 0",
    },
    teluguTitle: {
      fontFamily: "'Noto Sans Telugu', Lexend, sans-serif",
      textAlign: "center",
      fontSize: "13px",
      fontWeight: "700",
      marginBottom: "4px",
    },
    infoRow: { marginBottom: "4px" },
    h2: {
      fontSize: "11px",
      fontWeight: "700",
      margin: "6px 0 4px 0",
      borderBottom: "1px solid #000",
      paddingBottom: "2px",
    },
    treatmentItem: {
      margin: "4px 0",
      padding: "3px",
      backgroundColor: "#f5f5f5",
      border: "1px solid #ddd",
      fontSize: "11px",
    },
    footer: {
      textAlign: "center",
      borderTop: "1px dashed #000",
      fontSize: "8.5px",
      marginTop: "6px",
      paddingTop: "4px",
    },
    telugu: { fontFamily: "'Noto Sans Telugu', Lexend, sans-serif", fontSize: "11px" },
  };

  return (
    <div ref={pdfRef} style={styles.container}>
      <div style={styles.header}>
        <img
          alt="CropSync Logo"
          src="https://app.cropsync.in/logo_v.jpeg"
          style={styles.logo}
        />
        <div style={styles.companyName}>CropSync</div>
        <div style={styles.companyTag}>Smart Agricultural Solutions</div>
        <div style={{ fontSize: "9px" }}>www.cropsync.in | Tel: +91-9182867605</div>
      </div>

      <div style={styles.teluguTitle}>
        {problem_name_te ? problem_name_te : problem_name_en}
      </div>

      <div style={styles.infoRow}>
        <strong>Category:</strong> {category}
      </div>
      <div style={styles.infoRow}>
        <strong>Stage:</strong> {stage}
      </div>

      {symptoms_te && (
        <>
          <div style={styles.h2}>Symptoms</div>
          <div style={styles.telugu}>{symptoms_te.split("\n").map((s, i) => <div key={i}>{s}</div>)}</div>
        </>
      )}

      {notes_te && (
        <>
          <div style={styles.h2}>Advisory</div>
          <div style={styles.telugu}>{notes_te.split("\n").map((s, i) => <div key={i}>{s}</div>)}</div>
        </>
      )}

      {components && components.length > 0 && (
        <>
          <div style={styles.h2}>Treatment</div>
          {components.map((c, i) => (
            <div key={i} style={styles.treatmentItem}>
              <div style={{ fontWeight: "700" }}>{c.component_type || "-"}</div>
              <div style={{ fontSize: "11px" }}>
                <strong>Name:</strong>{" "}
                <span style={styles.telugu}>{c.component_name_te || "-"}</span>
              </div>
              {c.dose_te && (
                <div style={{ fontSize: "11px" }}>
                  <strong>Dose:</strong>{" "}
                  <span style={styles.telugu}>{c.dose_te}</span>
                </div>
              )}
              {c.application_method_te && (
                <div style={{ fontSize: "11px" }}>
                  <strong>Method:</strong>{" "}
                  <span style={styles.telugu}>{c.application_method_te}</span>
                </div>
              )}
              {c.notes_te && (
                <div style={{ fontSize: "11px" }}>
                  <strong>Note:</strong>{" "}
                  <span style={styles.telugu}>{c.notes_te}</span>
                </div>
              )}
            </div>
          ))}
        </>
      )}

      <div style={styles.footer}>
        <div>Receipt ID: {receipt_id}</div>
        <div>Date: {dateIST} IST</div>
        <div>Thank You for Using CropSync</div>
      </div>
    </div>
  );
}
